service: service-currencies
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  # You need to create an IAM role for your Lambda.
  iam:
    role: arn:aws:iam::12345678:role/AWSLambda

functions:
  api:
    handler: handler.listCurrencies
    events:
      - httpApi:
          path: /
          method: get
plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  patterns:
    - '!node_modules/**'
    - 'node_modules/node-fetch/**'